{
 "title": "system",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance) * 100",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Memory Usage (GBytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_Buffers_bytes + node_memory_Cached_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "cache"
    },
    {
     "expr": "node_memory_MemFree_bytes / 1024 / 1024 / 1024",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_SwapCached_bytes / 1024 / 1024 / 1024",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Disk Usage (MBytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]) / 1024 / 1024)",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]) / 1024 / 1024)",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Network Usage (MBytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total[5m]) / 1024 / 1024)",
     "legendFormat": "transmit"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total[5m]) / 1024 / 1024)",
     "legendFormat": "receive"
    }
   ]
  }
 ]
}