name: Build deltaquery
on:
  workflow_dispatch:
  push:
    tags:
      - 20[0-9]+-[0-9]+-[0-9]+
jobs:
  build:
    uses: ./.github/workflows/dockerfiles.yaml
    with:
      image: ingkle/deltaquery
      path: ./dockerfiles
      build_runner: self-hosted
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
